name: flutter_hsvcolor_picker_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_hsvcolor_picker:
    path: ../

flutter:
  uses-material-design: true
  
  assets:
   - packages/Avatar.jpg